# Generated by Django 5.2.6 on 2025-09-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('url_video', models.URLField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
